### ISSUE TITLE
Error while doing sails lift

### ISSUE THREAD

**Issue by Srini94** [sujanadiga-practo/Project-CDFIFM#3]
srinivasan@satish-HP-Notebook:~/git_srinivasan/Project-CDFIFM/web$ sails lift

info: Starting app...

module.js:340
    throw err;
    ^
Error: Cannot find module 'skipper'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/srinivasan/git_srinivasan/Project-CDFIFM/web/config/http.js:12:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/lib/node_modules/sails/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
    at requireAll (/usr/lib/node_modules/sails/node_modules/include-all/index.js:44:9)
    at buildDictionary (/usr/lib/node_modules/sails/node_modules/sails-build-dictionary/index.js:68:14)
    at Function.module.exports.aggregate (/usr/lib/node_modules/sails/node_modules/sails-build-dictionary/index.js:190:9)
srinivasan@satish-HP-Notebook:~/git_srinivasan/Project-CDFIFM/web$

**Comment by sujanadiga-practo** [comment]
@Srini94, You need do `sudo npm install` after cloning.
Refer [README.md](https://github.com/sujanadiga-practo/Project-CDFIFM/blob/master/README.md)
